print('API-1')
print('API-2')
print('Feature-1')
print('Feature-2')
print('Dev1')
print('Dev2')
print('Devops1')
print('Devops2')
print('Application 1')
print('Application 2')
print('Store 1')
print('Store 2')